// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ln_feature                      19
#define gattdb_location_and_speed              21
#define gattdb_position_quality                24
#define gattdb_ln_control_point                26
#define gattdb_navigation                      29
#define gattdb_alert_status                    33
#define gattdb_ringer_setting                  36
#define gattdb_ringer_control_point            39
#define gattdb_tx_power_level                  42

#endif
